"""增强用户系统数据模型字段

Revision ID: a79b0b115a1a
Revises: ad8022c76f21
Create Date: 2025-10-01 14:31:40.380781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79b0b115a1a'
down_revision = 'ad8022c76f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('prediction_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('prediction_result', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('prediction_metadata', sa.Text(), nullable=True))
        batch_op.drop_column('prediction_id')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('investment_experience', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('risk_preference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('preferences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notification_settings', sa.Text(), nullable=True))
        batch_op.drop_column('notification_preferences')

    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('notes')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_preferences', sa.TEXT(), nullable=True))
        batch_op.drop_column('notification_settings')
        batch_op.drop_column('preferences')
        batch_op.drop_column('risk_preference')
        batch_op.drop_column('investment_experience')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('nickname')

    with op.batch_alter_table('user_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prediction_id', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('prediction_metadata')
        batch_op.drop_column('prediction_result')
        batch_op.drop_column('prediction_type')
        batch_op.drop_column('model_type')

    # ### end Alembic commands ###
